### ISSUE TITLE
[Bug]：Could not find ShapeDrawable-3.2.aar

### ISSUE THREAD

**Issue by octopusYan** [getActivity/ShapeView#101]
### 框架版本【必填】

9.2

### 问题描述【必填】

9.2版本依赖的ShapeDrawable3.2版本在JitPakc仓库无法找到，报错 Could not find ShapeDrawable-3.2.aar

### 复现步骤【必填】

引用该项目9.2版本

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

小米

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform ShapeDrawable-3.2.aar (com.github.getActivity:ShapeDrawable:3.2) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find ShapeDrawable-3.2.aar (com.github.getActivity:ShapeDrawable:3.2).
        Searched in the following locations:
            https://jitpack.io/com/github/getActivity/ShapeDrawable/3.2/ShapeDrawable-3.2.aar
            https://jitpack.io/com/github/getActivity/ShapeDrawable/3.2/ShapeDrawable-3.2.jar
```

**Comment by getActivity** [comment]
<img width="657" alt="image" src="https://github.com/user-attachments/assets/3d41784c-4b1e-4815-9af2-3a14564c525c" />

经过核实，确实有这个问题，应该是 jitpack 的问题，目前我已经重构构建了，你可以重新试一下，不过我建议你更新到 [3.3](https://github.com/getActivity/ShapeDrawable/releases/tag/3.3) 的版本，该版本修复了 [ShapeView/issues/100](https://github.com/getActivity/ShapeView/issues/100) 问题

**Comment by octopusYan** [comment]
> 经过核实，确实有这个问题，应该是 jitpack 的问题，目前我已经重构构建了，你可以重新试一下，不过我建议你更新到 [3.3](https://github.com/getActivity/ShapeDrawable/releases/tag/3.3) 的版本，该版本修复了 [ShapeView/issues/100](https://github.com/getActivity/ShapeView/issues/100) 问题

好的，感谢支持
