### ISSUE TITLE
希望增加设置ripple属性

### ISSUE THREAD

**Issue by DuShuYuan** [getActivity/ShapeView#11]
范围跟随圆角设置

**Comment by getActivity** [comment]
@DuShuYuan 小伙子，经过慎重考虑，暂时不考虑加入水波纹效果，主要原因有两个：

1. 水波纹效果只能 Android 5.0 才可以使用，开发难度和工作量较高

2. 使用水波纹的人群少，大多数人都是选择只使用 shape 来做背景

**Comment by DuShuYuan** [comment]
> @DuShuYuan 小伙子，经过慎重考虑，暂时不考虑加入水波纹效果，主要原因有两个：
> 
> 1. 水波纹效果只能 Android 5.0 才可以使用，开发难度和工作量较高
> 2. 使用水波纹的人群少，大多数人都是选择只使用 shape 来做背景

水波纹一直在用
加入水波纹效果是不太方便，因为和阴影不搭。。。。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
