### ISSUE TITLE
不能预览吗

### ISSUE THREAD

**Issue by lydlovezjr** [getActivity/ShapeView#12]
如题

**Comment by lydlovezjr** [comment]
<img width="694" alt="企业微信截图_20210907142513" src="https://user-images.githubusercontent.com/19246347/132294958-22d67652-11fe-4da7-9312-c898e48d1a5b.png">

**Comment by lydlovezjr** [comment]
发现问题了,背景颜色不能直接使用background设置.
必须使用shape_solidColor啊.

**Comment by getActivity** [comment]
小伙子，background 是系统定义的属性，不是框架定义的属性。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
