### ISSUE TITLE
代码设置shapeDrawableBuilder.solidColor无效果

### ISSUE THREAD

**Issue by crazyzjw** [getActivity/ShapeView#13]
`val llybg=holder.getView<ShapeLinearLayout>(R.id.lly_item_bg)

                if (item.isChecked){
                    llybg.shapeDrawableBuilder.solidColor = context.resources.getColor(R.color.color_FFF8E5)
                    holder.setTextColor(R.id.tv_item_title,context.resources.getColor(R.color.color_FFBB00))
    
                }else{
                    llybg.shapeDrawableBuilder.solidColor = context.resources.getColor(R.color.color_F8F8F8)
                    holder.setTextColor(R.id.tv_item_title,context.resources.getColor(R.color.color_242925))
                }`

**Comment by getActivity** [comment]
小伙子，你调用 intoBackground 方法了吗？

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
