### ISSUE TITLE
设置了背景线性渐变后，阴影效果就会失效了？这是互斥的原因吗？

### ISSUE THREAD

**Issue by kanfRUI** [getActivity/ShapeView#14]
代码如下
<com.hjq.shape.view.ShapeTextView
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_margin="10dp"
        android:gravity="center"
        android:padding="10dp"
        android:text="垂直线性渐变"
        android:textColor="@android:color/black"
        android:textSize="14sp"
        app:shape="rectangle"
        app:shape_angle="90"
        app:shape_endColor="#ffdff8f0"
        app:shape_startColor="#fff7fefe"
        app:shape_shadowSize="9dp"
        app:shape_shadowColor="#50000000"
        app:shape_shadowOffsetX="5dp"
        app:shape_shadowOffsetY="5dp"
        app:shape_topLeftRadius="12dp"
        app:shape_topRightRadius="12dp"
        app:shape_bottomRightRadius="12dp"
        app:shape_bottomLeftRadius="0dp"
        />

**Comment by getActivity** [comment]
小伙子，我这几天研究了一下这个问题，发现无法从源码的角度解决这个问题，这是因为设置渐变色的方法是 Paint.setShader，而设置阴影的方法是 Paint.setShadowLayer，这两个 API 同时使用时会出现一个问题，会导致阴影失效，目前我也没有找到解决方案，不过对于你的需求，我想到了一个好的处理方案，你可以参考一下：

```xml
<com.hjq.shape.layout.ShapeFrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:shape="rectangle"
    app:shape_bottomLeftRadius="0dp"
    app:shape_bottomRightRadius="12dp"
    app:shape_shadowColor="#50000000"
    app:shape_shadowOffsetX="5dp"
    app:shape_shadowOffsetY="5dp"
    app:shape_shadowSize="9dp"
    app:shape_solidColor="#00000001"
    app:shape_topLeftRadius="12dp"
    app:shape_topRightRadius="12dp" >

    <com.hjq.shape.view.ShapeTextView
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_margin="10dp"
        android:gravity="center"
        android:padding="10dp"
        android:text="垂直线性渐变"
        android:textColor="@android:color/black"
        android:textSize="14sp"
        app:shape="rectangle"
        app:shape_angle="90"
        app:shape_bottomLeftRadius="0dp"
        app:shape_bottomRightRadius="12dp"
        app:shape_endColor="#ffdff8f0"
        app:shape_startColor="#fff7fefe"
        app:shape_topLeftRadius="12dp"
        app:shape_topRightRadius="12dp" />

</com.hjq.shape.layout.ShapeFrameLayout>
```

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。

**Comment by getActivity** [comment]
[ShapeView-6.2.aar.zip](https://github.com/getActivity/ShapeView/files/7275987/ShapeView-6.2.aar.zip)

**Comment by getActivity** [comment]
@kanfRUI 小伙子，问题已经修复了，你可以下载这个包测试看看，如果有问题可以反馈给我，没有问题的话我会在近期发布新版本。
