### ISSUE TITLE
设置指定方向的阴影

### ISSUE THREAD

**Issue by lucky-you** [getActivity/ShapeView#16]
现在设置了阴影，默认就是四个方向都会出现阴影，能否增加一个设置指定方向阴影的属性？

**Comment by getActivity** [comment]
小伙子，框架的阴影是用原生的 Paint.setShadowLayer 进行绘制的，我这边查了一下，Paint 没有提供任何设置某个角的阴影的方法，实现起来有难度，考虑到这个需求并不常见，另外某一个角没有阴影的效果给人的感觉很奇怪，所以我决定暂不实现它，把时间和精力留在其他框架的开发上面，

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
