### ISSUE TITLE
implementation ShapeView后，编译出现AAPT错误。

### ISSUE THREAD

**Issue by eagle518** [getActivity/ShapeView#17]
我的工程只要添加ShapeView库，编译出现以下出错，不得解：

xxx\src\main\res\values\strings.xml:1238:5-115: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

去除ShapeView即编译正常。

**Comment by getActivity** [comment]
小伙子，框架的 Demo 会出现这个问题吗？

**Comment by eagle518** [comment]
> 小伙子，框架的 Demo 会出现这个问题吗？

不会，在我另外两个工程里也不会；现在也不知道是跟这个项目的哪个配置之类的冲突了，找了几小时没找到原因。

**Comment by getActivity** [comment]
小伙子，我自己的话怎么试都是没有出现这个问题的，所以只能靠你自己去排查问题了，等你排查到原因了再反馈给我吧。

**Comment by getActivity** [comment]
小伙子，我自己的话怎么试都是没有出现这个问题的，所以只能靠你自己去排查问题了，等你排查到原因了再反馈给我吧。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
