### ISSUE TITLE
能否考虑支持foreground?

### ISSUE THREAD

**Issue by xxxifan** [getActivity/ShapeView#18]
有个对ImageView加遮罩的需求，我用的ShapeImageView，如果加一层ShapeFrameLayout之类的，略显繁琐了，如果能直接支持foreground相关属性就完美了，希望作者大大能考虑下，谢谢。

**Comment by getActivity** [comment]
不会支持，ShapeView 框架中的属性是针对 View 的背景，你如果要给前景设置，请手动定义 shape.xml 文件并设置给 View。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by xxxifan** [comment]
好的，谢谢回复
