### ISSUE TITLE
有没有想法加入阴影效果，在开发中是常见的。

### ISSUE THREAD

**Issue by candebbs** [getActivity/ShapeView#2]
如题

**Comment by getActivity** [comment]
小姑凉，暂时没有这个计划，因为框架的定位其实很明确，只针对原生 Shape 做封装，其他类型的封装暂时不考虑。

**Comment by getActivity** [comment]
你如果要实现的话，网上也有一些解决方案，可以供你可以参考：[https://github.com/lihangleo2/ShadowLayout](https://github.com/lihangleo2/ShadowLayout)

**Comment by getActivity** [comment]
当然不是没有可能加入阴影功能，但是主要取决于两个因素：

1. 这个框架用的人多不多
2. 提阴影需求的人多不多

**Comment by ZQ173** [comment]
> 当然不是没有可能加入阴影功能，但是主要取决于两个因素：
> 
> 1. 这个框架用的人多不多
> 2. 提阴影需求的人多不多

需要+1

**Comment by getActivity** [comment]
@candebbs @ZQ173 小伙子，阴影功能已经加上去了，你更新到最新版本即可。

**Comment by ZQ173** [comment]
太棒了轮子哥

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/147043062-84075fdd-ee3b-47fd-aa9c-0e885be71b28.png)
