### ISSUE TITLE
使用的5.0版本,在小米手机深色模式开启后，使用了下边几个layout后发现，有些页面可以很好的切到深色模式，有的就显示背景白色

### ISSUE THREAD

**Issue by tianshaokai** [getActivity/ShapeView#20]
1. ShapeConstraintLayout 
2. ShapeLinearLayout
3. ShapeRelativeLayout
4. ShapeFrameLayout

**Comment by tianshaokai** [comment]
嗯，我这边查了好多资料，我的代码里加了一个value-night的 theme 文件，这个导致的，如果想真正适配深色模式，是不是需要自己定义 深色模式的values文件才行

**Comment by getActivity** [comment]
你没有适配的话，就是你的问题了，小米的深色模式处理方式本身就比较简单粗暴，如果想达到你的预期是不可能的，如果你想要达到预期的效果，还是得自己适配夜间模式。

**Comment by getActivity** [comment]
小伙子，这个问题不属于框架的问题，你这边看看还有其他问题不？如果没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
关于适配的话，你可以看一下这个开源项目：[AndroidVersionAdapter](https://github.com/getActivity/AndroidVersionAdapter)，专门处理安卓版本适配的，夜间模式在那里面也有。
