### ISSUE TITLE
ShapeTextview不支持drawable的位置

### ISSUE THREAD

**Issue by LLQQHH** [getActivity/ShapeView#24]
想要有类似下面的属性
icon_normal_left/right/top/bottom | 图标 未选中 各方向
-- | --
icon_checked_left/right/top/bottom | 图标 选中 各方向
类似于Textview有drawLeft一样，你和这个好像不支持

**Comment by getActivity** [comment]
小伙子，ShapeTextView 是针对背景的 Drawable，不是针对 TextView 各个方向的 Drawable，这个你要明白，你如果要实现这块需求，请你自行定义 shape.xml 来实现，还有框架的出现目的是为了帮你少写 shape.xml 文件，而不是让你不用写 shape.xml 文件。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by LLQQHH** [comment]
本来我是用你这个
<com.hjq.shape.view.ShapeRadioButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="10dp"
                android:background="@null"
                android:gravity="center"
                android:padding="10dp"
                android:text="我是自定义按钮样式的 RadioButton"
                android:textSize="14sp"
                app:shape_buttonCheckedDrawable="@drawable/radiobutton_checked_ic"
                app:shape_buttonDisabledDrawable="@drawable/radiobutton_disable_ic"
                app:shape_buttonDrawable="@drawable/radiobutton_normal_ic" />
但是因为你这个图标默认是在文字的左边，而产品要求右边，我是想说不想因为一个位置，导致只能弃用ShapeRadioButton

**Comment by LLQQHH** [comment]
我是觉得可否针对TextView添加这个属性，这样ShapeRadioButton也可以用，毕竟他们是继承关系

**Comment by getActivity** [comment]
小伙子，这个建议不会被采纳，你自己通过 xml 来实现吧。

**Comment by LLQQHH** [comment]
ok
