### ISSUE TITLE
ShapeConstraintLayout设置了shape_radius不会作用到子view

### ISSUE THREAD

**Issue by yingka** [getActivity/ShapeView#25]
ShapeConstraintLayout设置了shape_radius，父容器里包含了一个ImageView，但是图片并没有被按照预想的被应用父容器设置的radius。

代码如下：
<com.hjq.shape.layout.ShapeConstraintLayout
                android:id="@+id/first"
                android:layout_width="124dp"
                android:layout_height="124dp"
                android:padding="1dp"
                app:shape_solidColor="@color/theme_color"
                android:layout_marginTop="@dimen/dimen_20"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/title"
                app:shape_radius="@dimen/dimen_14">

                <com.hjq.shape.view.ShapeImageView
                    android:id="@+id/iv_first"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:scaleType="centerCrop"
                    android:src="@mipmap/tj" />

                <ImageView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:src="@mipmap/icon_ghph_normal"
                    app:layout_constraintBottom_toBottomOf="@+id/iv_first"
                    app:layout_constraintEnd_toEndOf="@+id/iv_first" />

            </com.hjq.shape.layout.ShapeConstraintLayout>

**Comment by getActivity** [comment]
小伙子，请注意，这个框架只是帮你简化 shape 流程，不会帮你做任何裁剪，你用原生的 Shape 它来实现也是这样的。
