### ISSUE TITLE
需求：能否安排添加对各边单独设置阴影宽度（实际会遇到占位的宽度要求不一致的情况）

### ISSUE THREAD

**Issue by eagle518** [getActivity/ShapeView#26]
类似效果如下：
![1636623176(1)](https://user-images.githubusercontent.com/1551459/141274146-acb08946-b1d7-4445-9d01-3c6b13d80ff2.png)

已知官方不占位的CardView可以实现类似效果，但无法设置颜色值，所以不满足；其他各开源方案也都无法对各边单独控制。

**Comment by getActivity** [comment]
小伙子，我没听懂你的`设置影像`是什么意思？

**Comment by eagle518** [comment]
> 小伙子，我没听懂你说的`设置影像`是什么意思？

是“阴影”，特别是各边阴影宽度的设置。

**Comment by getActivity** [comment]
小伙子，目前框架的阴影效果采用的是 `Paint.setShadowLayer` 来实现的，这个 API 目前没有提供任何设置阴影各边宽度的设置，所以你这个需求在这个框架上面无法满足，我这边建议你采用其他方式来实现，如果你有更好的解决方案，也欢迎你给我提交代码。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
