### ISSUE TITLE
轮子哥，我刚才看这个好像支持ImageView？这个可以像官方的ShapeableImageView一样裁剪圆角或者圆形的图片吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/ShapeView#29]
![image](https://user-images.githubusercontent.com/54784104/150494844-eaa7befb-70d4-46c8-bef1-f25536f4809b.png)
![image](https://user-images.githubusercontent.com/54784104/150495087-99a8e0d0-bf3f-41a0-8a9e-3ef486bb04cf.png)
![image](https://user-images.githubusercontent.com/54784104/150495206-94e3a91b-dcd8-4dbd-8aea-0af37b976c2f.png)

**Comment by getActivity** [comment]
不行，小伙子，这个框架是针对 View 的 background 属性设置的，而不是 ImageView 的 src 属性设置的。

**Comment by SaltedFish-Extreme** [comment]
> 不行，小伙子，这个框架是针对 View 的 background 属性设置的，而不是 ImageView 的 src 属性设置的。

好的👌
