### ISSUE TITLE
迁移至androidx

### ISSUE THREAD

**Issue by xiejianping** [getActivity/ShapeView#31]
## 建议收集

官方已不再升级和维护support库，gradle.properties 若是不配置android.useAndroidX=true  android.enableJetifier=true  则无法使用ShapeTextView等控件

**Comment by getActivity** [comment]
如果转了，那么还停留在 Support 包的开发者应该怎么处理？

**Comment by xiejianping** [comment]
近几年的新项目应该都是androidx，如果是更早时间的项目用ShapeView 且还没迁移的应该也不会很多。若有也还可以用迁移前的版本,只是后续不维护而已

**Comment by getActivity** [comment]
那人家就是基于 Support 项目，并且想用最新版本呢？

**Comment by getActivity** [comment]
超过一个星期没有响应，关闭此 issue。
