### ISSUE TITLE
ShapeFrameLayout使用shape_solidDisabledColor的时候好像没效果

### ISSUE THREAD

**Issue by ender115** [getActivity/ShapeView#32]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）
无
* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
ShapeFrameLayout使用shape_solidDisabledColor的时候好像没效果，enabled已设为false
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
看下是否可以支持

**Comment by getActivity** [comment]
你这个属于 Bug，请通过提 Bug 单给我，而不是提建议单。

**Comment by getActivity** [comment]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/28616817/156877247-ec3388a8-3cb8-483b-8bac-7240eb6308d6.png">

**Comment by getActivity** [comment]
我用原生的 shape.xml 来实现也会出现这个问题，你确定用原生的 shape.xml 来实现没有问题？
