### ISSUE TITLE
ShapeFrameLayout使用shape_solidDisabledColor的时候好像没效果

### ISSUE THREAD

**Issue by ender115** [getActivity/ShapeView#33]
## 问题描述

* 框架版本：6.2

* 问题描述：ShapeFrameLayout使用shape_solidDisabledColor的时候好像没效果，enable已设为false

* 复现步骤：在ShapeFrameLayout使用shape_solidDisabledColor

* 是否必现：是

* 手机信息：小米 8se / Android 10

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）
全部
* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）
是
* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）
是
* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）
否
* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）
是
* 使用原生的 shape.xml 来实现是否也会出现该问题：是/否（排查一下是不是框架的代码存在问题导致的）
否
## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/28616817/156959166-72b2114b-db0d-449a-b10d-f0492b547980.png">

**Comment by ender115** [comment]
下面不是已经回答了么
