### ISSUE TITLE
ShapeFrameLayout使用shape_solidDisabledColor的时候好像没效果，enable已设为false

### ISSUE THREAD

**Issue by ender115** [getActivity/ShapeView#34]
## 问题描述

* 框架版本：6.2

* 问题描述：ShapeFrameLayout使用shape_solidDisabledColor的时候好像没效果，enable已设为false

* 复现步骤：ShapeFrameLayout使用shape_solidDisabledColor，enable设为false

* 是否必现：是

* 手机信息：xiaomi8 se / Android 10

## 请回答

* 是部分机型还是所有机型都会出现：全部

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：是

* 使用原生的 shape.xml 来实现是否也会出现该问题：否

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/28616817/158003278-4715a552-730b-4953-abb0-2099faf7be06.png">

**Comment by getActivity** [comment]
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/28616817/158003321-de831dcc-1ee6-405b-b335-34298e6e2fa4.png">

**Comment by getActivity** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/28616817/158003331-d10db390-faf6-4478-89cc-5af74234a4c8.png">
