### ISSUE TITLE
shapeview的attrs和新版的阿里百川套件的attrs冲突

### ISSUE THREAD

**Issue by jyjiawohao** [getActivity/ShapeView#35]

**Comment by getActivity** [comment]
这种情况下，只能二选一了，又或者把其中一个库拉下来改

**Comment by jyjiawohao** [comment]
<attr name="shape">
        
        <enum name="rectangle" value="0" />
        
        <enum name="oval" value="1" />
        
        <enum name="line" value="2" />
        
        <enum name="ring" value="3" />
    </attr>
看了下是shape命名重复导致的

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/164913212-c48666a3-2409-4a14-ac57-bb47c840bcfc.jpg)
