### ISSUE TITLE
是不是没有背景色的渐变方向设置？

### ISSUE THREAD

**Issue by liangjiajiajia** [getActivity/ShapeView#36]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
小伙子，你用原生的 Shape 是怎么设置背景渐变色方向的？

**Comment by liangjiajiajia** [comment]
shape_angle=270，可以了，原来的就有的属性
