### ISSUE TITLE
增加独立边框线的建议

### ISSUE THREAD

**Issue by candebbs** [getActivity/ShapeView#37]
在开发中，有碰到textView、editView只有底部等单边画上边框线，其它三边不用加，可不可以增加属性来设置左边，右边，上边，下边边框线独立设置有没有，或者不同颜色。

**Comment by getActivity** [comment]
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/28616817/169631496-aeceeddb-9e39-4ebd-b542-f47ccebc04c7.png">

**Comment by getActivity** [comment]
[ShapeView-8.2.aar.zip](https://github.com/getActivity/ShapeView/files/8747257/ShapeView-8.2.aar.zip)

**Comment by getActivity** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/28616817/169643220-2ecd6010-d5db-415c-94c2-48272ae04aa6.png">

**Comment by getActivity** [comment]
小伙子，关于线条重心方向的属性已经加上了，关于能不能设置多条边，这个是不会支持的，因为加上了它就不是线条了，线条只能有一条，建议你使用相对布局、自定义 View 、点九图等方式实现。

**Comment by candebbs** [comment]
好的，知道了，谢谢轮子哥！

**Comment by candebbs** [comment]
好的，知道了，谢谢轮子哥！
