### ISSUE TITLE
关于阴影问题请教

### ISSUE THREAD

**Issue by sdjwj1118** [getActivity/ShapeView#38]
## 问题描述

* 框架版本【必填】：8.0

* 问题描述【必填】：阴影

* 复现步骤【必填】：XXX

* 是否必现【必填】：填是/否

* 出现问题的手机信息【必填】：请填写出现问题的品牌和机型

* 出现问题的安卓版本【必填】：请填写出现问题的 Android 版本

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题【必答】：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的【必答】：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题【必答】：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：是/否（排查一下是不是框架的代码存在问题导致的）

框架的阴影很方便 但是在开发中遇到一个，比如一个view是宽180dp高200dp UI图上是20dp的阴影宽度 所以我在写布局的时候 高宽各加了 阴影宽度x2 ，但实际效果出来 不用阴影的180dp 200dp画出来的view 比用阴影180dp+ 20x2 200dp+20x2 画出来的要大一些，我想确认在用阴影的时候是不是我这样去计算增加view的高宽,理论上这样计算阴影的view画出来的应该和不带阴影的是一个大小，我指的是不含阴影处

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
* 
![image](https://user-images.githubusercontent.com/33438073/177035261-216b8571-308b-418d-98c6-3fce3cc86f1c.png)
![image](https://user-images.githubusercontent.com/33438073/177035270-cb8b1ffe-798b-4ab9-a4e4-fe980bce0a66.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/28616817/177043918-d31704db-9563-490e-9535-0c21c191cb32.png">
