### ISSUE TITLE
使用阴影和不使用阴影的view大小不一致

### ISSUE THREAD

**Issue by sdjwj1118** [getActivity/ShapeView#39]
## 问题描述

* 框架版本【必填】：8.2

* 问题描述【必填】：使用阴影和不使用阴影的view大小不一致框架的阴影很方便 但是在开发中遇到一个，比如一个view是宽180dp高200dp UI图上是20dp的阴影宽度 所以我在写布局的时候 高宽各加了 阴影宽度x2 ，但实际效果出来 不用阴影的180dp 200dp画出来的view 比用阴影180dp+ 20x2 200dp+20x2 画出来的要大一些，我想确认在用阴影的时候是不是我这样去计算增加view的高宽,理论上这样计算阴影的view画出来的应该和不带阴影的是一个大小，我指的是不含阴影处

* 复现步骤【必填】：XXX

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米10

* 出现问题的安卓版本【必填】：12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是
* 
* issue 是否有人曾提过类似的问题【必答】：是）

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：否
## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
* 
![image](https://user-images.githubusercontent.com/33438073/177044065-7b211eb4-8354-4704-9885-19db472d3555.png)
![image](https://user-images.githubusercontent.com/33438073/177044071-a9df8864-24b3-4934-9d95-80592e314711.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/28616817/177186047-6e703b80-9f7e-4dce-a200-aa0028216af5.png">

**Comment by getActivity** [comment]
@sdjwj1118 小伙子，一个宽高都为 170dp 带阴影的 View，如果阴影大小为 10dp，那么这个 View 除阴影之外的宽高应该为 150dp，我做了一下测试，两个 View 显示的内容都差不多，虽然说有误差，误差都比较小，但是避免不了，并没有你给的截图上差那么多的。

**Comment by getActivity** [comment]
```xml
<com.hjq.shape.view.ShapeTextView
    android:layout_width="170dp"
    android:layout_height="170dp"
    android:layout_margin="10dp"
    android:clickable="true"
    android:gravity="center"
    android:paddingTop="30dp"
    android:paddingBottom="30dp"
    android:text="默认阴影颜色"
    android:textColor="@android:color/black"
    android:textSize="14sp"
    app:shape="rectangle"
    app:shape_radius="10dp"
    app:shape_shadowColor="#20000000"
    app:shape_shadowSize="10dp"
    app:shape_solidColor="#FFFFFF" />

<com.hjq.shape.view.ShapeTextView
    android:layout_width="150dp"
    android:layout_height="150dp"
    android:layout_margin="10dp"
    android:clickable="true"
    android:gravity="center"
    android:paddingTop="30dp"
    android:paddingBottom="30dp"
    android:text="默认阴影颜色"
    android:textColor="@android:color/black"
    android:textSize="14sp"
    app:shape="rectangle"
    app:shape_radius="10dp"
    app:shape_shadowColor="#20000000"
    app:shape_shadowSize="0dp"
    app:shape_solidColor="#FFFFFF" />
```

**Comment by getActivity** [comment]
[ShapeView-8.3.aar.zip](https://github.com/getActivity/ShapeView/files/9072261/ShapeView-8.3.aar.zip)

**Comment by getActivity** [comment]
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/28616817/178089892-8f57f19d-3665-4961-9389-30188be60acd.png">

**Comment by getActivity** [comment]
小伙子，远程依赖更新了，多留意下。
