### ISSUE TITLE
ShapeRecyclerView 使用shape_shadowSize页面错乱

### ISSUE THREAD

**Issue by GitHubWebb** [getActivity/ShapeView#41]
## 问题描述

* 框架版本【必填】：com.github.getActivity:ShapeView:8.0 8.2   ShapeView-8.3.aar

* 问题描述【必填】：使用shape_shadowSize页面会错乱, RecyclerView内容超出, 数据量小不明显,稍微多一些会看到内容从最底部滑动上去, 可看视频

* 复现步骤【必填】：只需要在代码中注释shape_shadowSize即可看到区别

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为Mate10 Mate30pro

* 出现问题的安卓版本【必填】：Android10

## 请回答

* 是部分机型还是所有机型都会出现【必答】：不确定 

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：否

## 其他

* 提供截图或视频（根据需要提供，此项不强制）

https://user-images.githubusercontent.com/24510234/180600382-23ac0d72-ee16-44ab-8b9a-7989eb940803.mp4

https://user-images.githubusercontent.com/24510234/180600415-eabea089-0d4b-4b9f-8f6f-e88900371ebd.mp4

* 提供解决方案（如果已经解决了的话，此项不强制）
<img width="582" alt="image" src="https://user-images.githubusercontent.com/24510234/180600443-2f69a553-ff4f-4381-b808-89cc4378fb67.png">
只需要去除app:shape_shadowSize="@dimen/dp_10"即可

**Comment by getActivity** [comment]
小伙子，这个不是 Bug，是属于正常现象，你认为是 Bug，可能来源于你对框架的认知有误

1. 框架的实现原理是采用设置 View 的背景 Drawable 来实现的
2. Drawable 中阴影区域的画布就是一个透明的 + 渐变色来实现的

**Comment by GitHubWebb** [comment]
> 小伙子，这个不是 Bug，是属于正常现象，你认为是 Bug，可能来源于你对框架的认知有误
> 
> 1. 框架的实现原理是采用设置 View 的背景 Drawable 来实现的
> 2. Drawable 中阴影区域的画布就是一个透明的 + 渐变色来实现的

也许对框架的认知有误, 但正常粗略的理解 RecyclerView的使用是承载列表数据, Shape是对View显示形式进行改变, 颜色 / 形状
现在框架的现象违背了一直以来的使用rv 和 shape 观念感受
应该大部分人的理解就是 RecyclerVIew正常渲染列表的样式渲染item, 都包裹在RecyclerView中
而ShapeRecyclerView 是可以在"原基础"上对形状进行改造 进行扩展

现在使用ShapeRecyclerView却会导致正常rv不会出现的现象, 内容居然超出包裹盒子, 难道不是很奇怪么

**Comment by GitHubWebb** [comment]
换言之, 大家使用ShapeRecyclerView目的应该跟我类似, 要实现圆角阴影效果的列表。
如果轮子哥认为是我认知的问题, 那ShapeRecyclerView的正确应用场景应该是什么样子
因为做这些app没有遇到过会有内容超过包裹盒子展示的需求

**Comment by GitHubWebb** [comment]
在轮子哥的指引下 该问题通过修改xml代码的方式 已解决
给 RecyclerView 设置同等阴影大小的 padding 属性即可
android:paddingBottom="@dimen/dp_10"
