### ISSUE TITLE
建议提供EditText的支持

### ISSUE THREAD

**Issue by liyuzhao** [getActivity/ShapeView#42]
设计师给的UI有的EditText的背景是矩形的，有的是两边是圆形的，看着您实现的TextView挺像，但无法直接用。 最好可以有个类产出是Drawable。 这样EditText设置下background就可以实现不同的形状了。 

只是建议哈，如有实现难度，请忽略。

**Comment by getActivity** [comment]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/28616817/184609013-9c9c6d8e-63a9-4c17-9d51-c4fa49a6c947.png">
