### ISSUE TITLE
渐变色背景和纯色背景切换异常

### ISSUE THREAD

**Issue by qicolor** [getActivity/ShapeView#43]
## 问题描述

* 框架版本【必填】：8.3

* 问题描述【必填】：纯色背景切换为渐变色的时候正常，反切换的时候就出现了异常 无法切换为纯色背景

* 复现步骤【必填】：首先通过xml设置纯色背景，然后再代码中设置为渐变色背景最后再切换会纯色背景就无法切换成功
              if (isShow) {
                    shapeButton.getShapeDrawableBuilder()
                            .setSolidGradientColors(0xFFFFFFF, 0xFF000000)
                            .intoBackground();
                } else {
                    shapeButton.getShapeDrawableBuilder()
                            .setSolidColor(0xFF000000)
                            .intoBackground();
                }

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：红米k30 vivo v1838A

* 出现问题的安卓版本【必填】：android 12以及android 11
## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
[ShapeView-8.3.aar.zip](https://github.com/getActivity/ShapeView/files/9386238/ShapeView-8.3.aar.zip)

**Comment by getActivity** [comment]
小伙子，经过验证，确实有问题，问题已经修复了。

**Comment by qicolor** [comment]
以及正常使用了
