### ISSUE TITLE
设置布局为宽度wrap_content 动态给布局设置外边框 会导致布局宽度直接撑满

### ISSUE THREAD

**Issue by sdjwj1118** [getActivity/ShapeView#44]
## 问题描述

* 框架版本【必填】：8.3

* 问题描述【必填】：设置布局为宽度wrap_content 动态给布局设置外边框 会导致布局宽度直接撑满

* 复现步骤【必填】：设置布局为宽度wrap_content 动态给布局设置外边框 会导致布局宽度直接撑满（注意：目前不受理没有复现步骤的 Bug 单）

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：请填写出现问题的品牌和机型 小米10U

* 出现问题的安卓版本【必填】：请填写出现问题的 Android 版本 12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分/全部（例如：某为，某 Android 版本会出现） 未测试其他机型

* 框架最新的版本是否存在这个问题【必答】：是/否（如果用的是旧版本的话，建议升级看问题是否还存在） 是

* 是否已经查阅框架文档还未能解决的【必答】：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的） 是

* issue 是否有人曾提过类似的问题【必答】：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）无

* 是否可以通过 Demo 来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）是

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：是/否（排查一下是不是框架的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
* <com.hjq.shape.layout.ShapeRelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/srl_item"
    android:layout_width="wrap_content"
    android:layout_height="32dp"
    android:minWidth="60dp"
    android:paddingLeft="21dp"
    android:paddingRight="21dp"
    app:shape_radius="5dp"
    app:shape_strokeColor="#CFD7E6"
    app:shape_strokeWidth="1dp"/>

if (!carPictureBean.isSelected) {
                        itemBinding.srlItem.shapeDrawableBuilder.setStrokeWidth(1.dp.toInt())
                            .setStrokeColor("#CFD7E6".toColorInt()).intoBackground()
                        itemBinding.srlCorrect.isVisible = false
                    } else {
                        itemBinding.srlItem.shapeDrawableBuilder.setStrokeWidth(2.dp.toInt())
                            .setStrokeColor("#000000".toColorInt()).intoBackground()
                        itemBinding.srlCorrect.isVisible = true
                    }

我的布局设置为了宽度自适应 但是有个最小值为60dp 布局用作在rv上，通过点击item我动态给布局加上边框 整个布局就直接撑满了
![e686a64a05504fb48be9c5752327ae8](https://user-images.githubusercontent.com/33438073/188089174-e59d1de9-6630-484d-ad3b-1933b3131c8d.jpg)
![a542485497e3867c265e2ca33e68ccb](https://user-images.githubusercontent.com/33438073/188089229-e9948344-4157-4809-bb2a-5950c297120d.jpg)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/28616817/188140919-b5eca108-c55f-4744-b074-5732eaba7ee0.png">

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写
