### ISSUE TITLE
使用ShapeRelativeLayout的时候给布局设置宽度为wrap_content minWidth="60dp" 通过代码修改该布局的setStrokeWidth和setStrokeColor 布局宽度会直接撑满

### ISSUE THREAD

**Issue by sdjwj1118** [getActivity/ShapeView#45]
## 问题描述

* 框架版本【必填】：8.3

* 问题描述【必填】：使用ShapeRelativeLayout的时候给布局设置宽度为wrap_content minWidth="60dp" 通过代码修改该布局的setStrokeWidth和setStrokeColor 布局宽度会直接撑满

* 复现步骤【必填】：给ShapeRelativeLayout设置最小宽度 再通过代码修改边框和（注意：目前不受理没有复现步骤的 Bug 单）

* 是否必现【必填】：填是/否 是

* 出现问题的手机信息【必填】：请填写出现问题的品牌和机型 小米10u

* 出现问题的安卓版本【必填】：请填写出现问题的 Android 版本 android 12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分/全部（例如：某为，某 Android 版本会出现）所有

* 框架最新的版本是否存在这个问题【必答】：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）是

* 是否已经查阅框架文档还未能解决的【必答】：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）是

* issue 是否有人曾提过类似的问题【必答】：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）否

* 是否可以通过 Demo 来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）是

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：是/否（排查一下是不是框架的代码存在问题导致的）否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
* 
![a542485497e3867c265e2ca33e68ccb](https://user-images.githubusercontent.com/33438073/188254872-88320aa5-0b6a-47eb-9cbf-6fd100df245a.jpg)
![e686a64a05504fb48be9c5752327ae8](https://user-images.githubusercontent.com/33438073/188254875-14a35bb0-0bf5-4516-ae98-f561fc5b0b7d.jpg)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/28616817/188300366-bf8c1887-5bb5-4e19-88d5-edd3e60acacb.png">

<img width="914" alt="image" src="https://user-images.githubusercontent.com/28616817/188300370-f049b1a0-2002-4850-8474-48cda2adad95.png">

![screenshot1662272565526](https://user-images.githubusercontent.com/28616817/188300418-10ad245d-c0f9-471a-bdb6-f715c656ac29.png)

**Comment by getActivity** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/28616817/188300478-17903d0c-bdee-4ddc-983d-005bc3c0174b.png">

@sdjwj1118 按照你说的步骤进行操作，我并没有复现到该问题，需要你这边提供一个可供复现的 Demo 工程到这里来。

**Comment by sdjwj1118** [comment]
已解决 是我布局的问题。还有个问题反馈下 使用shapebutton 文字居中 但实际文字是会偏高一点 
![image](https://user-images.githubusercontent.com/33438073/188864134-be11e9ee-a881-4a3a-af44-5cc3029b8657.png)

**Comment by sdjwj1118** [comment]
<img width="503" alt="1662548876234" src="https://user-images.githubusercontent.com/33438073/188864158-8ec0de74-baa3-486e-b391-65068aa1c24a.png">

**Comment by getActivity** [comment]
@sdjwj1118 小伙子，你换成原生的 shape.xml 是否也有同样的问题。

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
