### ISSUE TITLE
设置 solidColor 颜色后，如何动态 删除solidColor 设置呢

### ISSUE THREAD

**Issue by tianshaokai** [getActivity/ShapeView#46]
设置 solidColor 颜色后，如何动态 删除solidColor 设置呢

* 框架版本【必填】：v8.3

* 问题描述【必填】：有个需求选中时设置了 solidColor，想取消选中时，删除 solidColor，不知道使用哪个api 删除

* 复现步骤【必填】：列表 点击 

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：所有手机
* 出现问题的安卓版本【必填】：所有版本

**Comment by getActivity** [comment]
[ShapeView-8.5.aar.zip](https://github.com/getActivity/ShapeView/files/9497083/ShapeView-8.5.aar.zip)

**Comment by getActivity** [comment]
```java
shapeView.getShapeDrawableBuilder()
    .setSolidColor(ContextCompat.getColor(context, android.R.color.transparent))
    .intoBackground();
```

**Comment by getActivity** [comment]
@tianshaokai 小伙子，你下载上面最新的包，然后调用上面的代码试一下

**Comment by tianshaokai** [comment]
可以了，8.5 版本可以了

**Comment by getActivity** [comment]
那就行，小伙子，你先用这个包，等后续远程依赖发布了，你再更新上去

**Comment by tianshaokai** [comment]
什么时候更新8.5版本代码啊

**Comment by getActivity** [comment]
@tianshaokai 远程依赖已经更新了，后续多留意一下
