### ISSUE TITLE
UI样式建议

### ISSUE THREAD

**Issue by billdizl** [getActivity/ShapeView#48]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】
![image](https://user-images.githubusercontent.com/30317994/190143592-92638513-880b-4c75-bdbf-6bc02bdfa7ef.png)
如图 右上角的三角形样式 ,该框架无法shape出来,建议增加样式

**Comment by getActivity** [comment]
小伙子，暂时不考虑做三角形的情况，建议通过切图或者自定义 View 来实现。

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
