### ISSUE TITLE
代码中动态设置不生效！因为源码中只返回控件本身并没有刷新

### ISSUE THREAD

**Issue by LLQQHH** [getActivity/ShapeView#5]

**Comment by getActivity** [comment]
小伙子，你调用 set 方法并不会立即生效，只是对参数的一些设置，只有调用 intoBackground 或者 intoTextColor 才会生效。

**Comment by LLQQHH** [comment]
比如在RecycleView中 根据不同的条件要显示不同的背景，如果每次都调用intoBackground ，我看了你的源码每次都重新产生一个drawable再设置背景，感觉在列表中影响性能，甚至卡顿！建议把draw变成成员变量，如果存在已经设置的draw，只要更新drawable的参数，然后notify，drawable这样会比较好！

**Comment by getActivity** [comment]
小伙子，我问你一个问题，GradientDrawable 是怎么绘制到屏幕的？

**Comment by getActivity** [comment]
小伙子，我想你可能有一个误区，GradientDrawable 本身不会占用太大的内存，你可以看 GradientDrawable.draw() 方法，都是用画笔画的，相比 BitmapDrawable 对象，它不需要先将 Bitmap 加载进内存中，所以 GradientDrawable 内存占用自然就小了很多，至于你说的频繁创建 Drawable 对象，你平时使用的 getResources().getDrawable() 方法其实每次都会 new Drawable 对象。

**Comment by getActivity** [comment]
虽然对象复用这块属于可优化的空间，但是我觉得作用并不大，并不是不能实现，而是会破坏框架原有的设计，从而导致开发和维护成本花销变得更大，所以暂时不考虑去做。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by LyricGan** [comment]
v5.0版本，修改属性参数后调用intoBackground()状态未生效，看示例未提供相关测试代码，作者再看下

**Comment by getActivity** [comment]
@LyricGan 小伙子，麻烦你提供一下调用的代码，我来做一下测试。

**Comment by LyricGan** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical">

    <com.hjq.shape.view.ShapeView
        android:id="@+id/shape_view"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_marginTop="16dp"
        app:shape="rectangle"
        app:shape_bottomLeftRadius="5dp"
        app:shape_solidColor="@android:color/black"
        app:shape_topLeftRadius="5dp"
        app:shape_topRightRadius="5dp" />

    <Button
        android:id="@+id/btn_change"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="16dp"
        android:text="Change" />
</LinearLayout>`

`public class TestActivity extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test);
        ShapeView shapeView = findViewById(R.id.shape_view);
        findViewById(R.id.btn_change).setOnClickListener(v -> shapeView.setSolidColor(Color.BLUE).intoBackground());
    }
}`
测试代码如上，看看是不是调用的问题

**Comment by szw930406a** [comment]
3.3升到5.0 
setSolidColor后调用intoBackground() 未生效
setStrokeColor后调用intoBackground() 生效
