### ISSUE TITLE
建议升级到AndroidX/支持AndroidX

### ISSUE THREAD

**Issue by qazxcs113** [getActivity/ShapeView#52]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】是

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】看了issue,你这边是希望兼容底层support中去支持.但是我感觉你也可以多用一个包去兼容AndroidX. 因为到后面我希望的是去掉enableJetifier  使得我的项目编译更快一些。 

* 你觉得该怎么去完善会比较好？【非必答】可以参考一个RxView中的关于Fragment中的做法，用另外一个包.支持AndroidX

**Comment by getActivity** [comment]
不，我拒绝，因为这样我要维护两套代码，你的项目编译时间是减少了，但是我的代码维护成本变高了，你的痛苦并没有消失，只是转移到了我身上而已。

**Comment by getActivity** [comment]
当然并不是不能实现，你如果硬是要求一定要是依赖 AndroidX 也不是没有办法，你可以用谷歌官方提供的 [Jetifier 工具](https://developer.android.google.cn/studio/command-line/jetifier)，将框架的 aar 下载下来进行转换，不过我感觉你没有这个必要，更实在点的办法是，下次换电脑记得多花 money 买个高配置的，这样不但你的编译时间变快了，同时电脑其他方面也会变流畅。

**Comment by qazxcs113** [comment]
理解万岁,加钱能解决的事情，当然是最好了。but~公司的电脑并没有给太多的机会。
谢谢给出的方案,

**Comment by hxmeie** [comment]
放弃support吧
