### ISSUE TITLE
在不同机型上面适配有问题

### ISSUE THREAD

**Issue by Mrliandroid** [getActivity/ShapeView#53]
#### 问题描述

* 框架版本【必填】：
com.github.getActivity:ShapeView:8.5
* 问题描述【必填】：在oppo 手机上面机型是安卓12 跟设计图符合度比较高，在华为荣耀8 上面跟设计图出入比较大，不同机型表现的不一样。

* 复现步骤【必填】：可以测试一下不同机型

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为荣耀8 

* 出现问题的安卓版本【必填】：安卓8.0

* 问题信息的来源渠道【必填】：自己项目开发过程中遇到的bug

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分机型 华为荣耀8 

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：下面有代码

* 使用原生的 shape.xml 

> 来实现是否也会出现该问题【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制） 下面有截图

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by Mrliandroid** [comment]
![image](https://user-images.githubusercontent.com/76427825/202393947-5833ae0d-9cc1-4cc0-8f41-e9a60d51020c.png)

**Comment by Mrliandroid** [comment]
![image](https://user-images.githubusercontent.com/76427825/202394451-5987dc3e-1098-4c44-93fe-091cd4a92709.png)

**Comment by Mrliandroid** [comment]
<com.hjq.shape.layout.ShapeLinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="@dimen/sw_5dp"
                android:layout_marginRight="@dimen/sw_5dp"
                android:orientation="vertical"
                app:shape="rectangle"
                app:shape_radius="@dimen/sw_10dp"
                app:shape_shadowColor="@color/shadow_color"
                app:shape_shadowOffsetX="@dimen/sw_5dp"
                app:shape_shadowOffsetY="@dimen/sw_7dp"
                app:shape_shadowSize="@dimen/sw_10dp"
                app:shape_solidColor="#FFFFFF">

**Comment by Mrliandroid** [comment]
<color name="shadow_color">#50000000</color>

**Comment by Mrliandroid** [comment]
<color name="shadow_color">#50000000</color>

**Comment by getActivity** [comment]
小伙子，Github 提供的 Demo 工程是否也有这个问题？

**Comment by Mrliandroid** [comment]
demo也有这个问题

**Comment by Mrliandroid** [comment]
![Uploading image.png…]()

**Comment by getActivity** [comment]
已在 QQ 上面答复
