### ISSUE TITLE
 Check属性问题

### ISSUE THREAD

**Issue by 287138531** [getActivity/ShapeView#54]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）
没有
* 框架文档是否有提及到此问题？【必答】：是/否（请先看完框架的文档后再来提建议）
没有
* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）
ShapeCheckBox 或者 ShapeRadioButton  希望加个属性默认不需要图标。或者Shapetextview 支持 Check属性，目前测试下来是不支持的
* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
小伙子，ShapeCheckBox 和 ShapeRadioButton 默认没有图标好像不太合理吧？没有人会这样做吧？你想想后面点击了它，突然显示出了一个图标，松手这个图标又没了，你难道不觉得这样很奇怪么？

**Comment by 287138531** [comment]
不是说，默认不需要图标，是加个属性去掉一些ShapeCheckBox 或者 ShapeRadioButton 默认的样式，如果要多个属性去掉就违背效率这个初衷了，还不如写drawble，其实要是textview支持Check属性，也没要反向操作了。很多时候喜欢用textview代替一些控件就是因为textview本身没带一些默认的属性，内间距之类的，可塑性强。。国内设计师基本没有按照安卓规范设计的。。

**Comment by getActivity** [comment]
[ShapeView-9.0.aar.zip](https://github.com/getActivity/ShapeView/files/10048342/ShapeView-9.0.aar.zip)

**Comment by getActivity** [comment]
```
<com.hjq.shape.view.ShapeCheckBox
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="10dp"
    android:background="@null"
    android:gravity="center"
    android:padding="10dp"
    android:text="我是自定义按钮样式的 CheckBox"
    android:textSize="14sp"
    app:shape_buttonDrawable="@null" />
```

**Comment by getActivity** [comment]
小伙子，你可以下载上面的 aar 包，然后使用 `app:shape_buttonDrawable="@null"` 属性即可去除 ShapeCheckBox/ShapeRadioButton 默认自带的图标。

**Comment by 287138531** [comment]
明白了，我自己扩展了个CheckedTextView。。。。
