### ISSUE TITLE
在小屏尺寸的屏幕的适配上面有问题

### ISSUE THREAD

**Issue by TianTingting** [getActivity/ShapeView#55]
问题描述
框架版本【必填】：
com.github.getActivity:ShapeView:8.5

问题描述【必填】：在小屏手机上超过一屏幕的内容就不显示线性布局；

复现步骤【必填】：可以测试一下不同小屏幕的机型

是否必现【必填】：是

出现问题的手机信息【必填】：小米6、vivo Y67

出现问题的安卓版本【必填】：安卓6.0

问题信息的来源渠道【必填】：自己项目开发过程中遇到的bug

请回答
是部分机型还是所有机型都会出现【必答】：部分机型 小米6

框架最新的版本是否存在这个问题【必答】：是

是否已经查阅框架文档还未能解决的【必答】：是

issue 是否有人曾提过类似的问题【必答】：否

是否可以通过 Demo 来复现该问题【必答】：是

来实现是否也会出现该问题【必答】：否

其他
提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

提供截图或视频（根据需要提供，此项不强制） 下面有截图

提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，你使用原汁原味的线性布局试一下是否有同样的问题？

**Comment by TianTingting** [comment]
有相同的问题的。具体布局：









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月24日(星期四) 晚上9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [getActivity/ShapeView] 在小屏尺寸的屏幕的适配上面有问题 (Issue #55)





 
小伙子，你使用原汁原味的线性布局试一下是否有同样的问题？

**Comment by getActivity** [comment]
@TianTingting 那这个就不是框架的问题了，需要你自行排查解决了。

**Comment by TianTingting** [comment]
就是里面的布局超过一屏幕就会出现这个问题。在小屏手机上







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月24日(星期四) 晚上9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [getActivity/ShapeView] 在小屏尺寸的屏幕的适配上面有问题 (Issue #55)





 
@TianTingting 那这个就不是框架的问题了，需要你自行排查解决了。

**Comment by TianTingting** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getActivity/ShapeView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [getActivity/ShapeView] 在小屏尺寸的屏幕的适配上面有问题 (Issue #55)





 
@TianTingting 那这个就不是框架的问题了，需要你自行排查解决了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

这个是你的那个框架的项目。直接嵌套超过一屏幕就会没有显示内容。在小屏手机上就不显示

**Comment by getActivity** [comment]
@TianTingting 小伙子，你用原生的线性布局都有这个问题，那只能说明是系统的问题或者你自己写法的问题了，需要你这边自行解决，我目前只处理和框架相关的问题（框架的 Bug 和建议）。

**Comment by TianTingting** [comment]
第二次截图是：https://github.com/getActivity/AndroidProject.这个里面项目，我就是运行的这个里面的代码，只不过把mineFragment布局中的LinearLayout换成了shapeLinarLayout



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月24日(星期四) 晚上10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [getActivity/ShapeView] 在小屏尺寸的屏幕的适配上面有问题 (Issue #55)





 
@TianTingting 小伙子，你用原生的线性布局都有这个问题，那只能说明是系统的问题或者你自己写法的问题了，需要你这边自行解决，我目前只处理和框架相关的问题（框架的 Bug 和建议）。

**Comment by TianTingting** [comment]
shape_shadowSize这个属性的值设置为0就可以显示，设置大于0就不显示。在小屏幕的手机上。这个是框架的bug还是我自己的布局问题。

**Comment by getActivity** [comment]
> 有相同的问题的。具体布局：

那我前面问你直接用 LinearLayout 是不是有同样问题，你为什么要回答有？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
