### ISSUE TITLE
一个ShapeLinearLayout 布局中使用了   "阴影 " shape_shadowSize 。 存在很多控件超过了屏幕  当shape_shadowSize 为 0时没问题，其他值时，ui就显示不了了

### ISSUE THREAD

**Issue by xiechunjiang** [getActivity/ShapeView#56]
#### 问题描述

* 框架版本【必填】：8.5

* 问题描述【必填】：一个ShapeLinearLayout 布局中使用了   "阴影 " shape_shadowSize 。 存在很多控件超过了屏幕  当shape_shadowSize 为 0时没问题，其他值时，ui就显示不了了

* 复现步骤【必填】：一个总ShapeLinearLayout  里面设置许多控件，设置这个ShapeLinearLayout  shape_shadowSize 大于0 ，超过屏幕有很多时，就会出现

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：畅想50

* 出现问题的安卓版本【必填】： Android10

* 问题信息的来源渠道【必填】：自己遇到的bug

#### 请回答

* 是部分机型还是所有机型都会出现【必答】： 预览布局时就看不见了

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：有，但是看着没解决方案

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：否

#### 其他
 `<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#F3F8FF">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_above="@+id/bottomLinear"
        >

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <com.hjq.shape.layout.ShapeLinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginLeft="10dp"
                android:layout_marginTop="5dp"
                android:layout_marginRight="10dp"
                android:orientation="vertical"
                android:paddingBottom="5dp"

                app:layout_constraintTop_toTopOf="parent"
                app:shape_radius="10dp"
                app:shape_shadowColor="#12032c6a"
                app:shape_shadowOffsetX="2dp"
                app:shape_shadowOffsetY="2dp"
                app:shape_shadowSize="10dp"
                app:shape_solidColor="#ffffff">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="反映人"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="王梓东"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="电话"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="15221234015"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="社员身份"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="区政协委员: 上海市"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="社情民意编号"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="222222"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="工作单位及职务"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="河南省郑州市"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="所属基层-支部"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="某某某支部"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="专委会/联谊会"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="专委会1"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="邮箱"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="dpsszewsnoh@gmail.com"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="报送人"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="办公室机关"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="信息是否公开"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="是"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="是否匿名"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="否"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="是否联名"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="标题"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="关于民主化的改革方案"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="信息分类"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="我是信息分类"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="信息小类"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="党建"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="20dp"
                    android:layout_marginRight="20dp"
                    android:text="正文"
                    android:textColor="#ff7a7c87"
                    android:textSize="14sp" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="20dp"
                    android:layout_marginTop="5dp"
                    android:layout_marginRight="20dp"
                    android:text="溢别想喜陈将阴浊耕想柬磁籼辈箱蛾颖橘抄皱掀鄂哎灼告其肾煮迁荀叨%汁挤丽雏摸俘前九飘恳网挖肋盛呢蔡署摸三变兼季拳脖龟昼帅祸瞎战他丝"
                    android:textColor="#ff26272d"
                    android:textSize="14sp" />

            </com.hjq.shape.layout.ShapeLinearLayout>

        </LinearLayout>
    </ScrollView>

    <LinearLayout
        android:id="@+id/bottomLinear"
        android:layout_width="match_parent"
        android:layout_height="80dp"
        android:layout_alignParentBottom="true"
        android:background="#ffffff"
        android:orientation="horizontal">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:layout_marginLeft="26dp"
            android:drawableTop="@mipmap/ic_launcher"
            android:text="更多" />

        <com.hjq.shape.layout.ShapeRelativeLayout
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:layout_marginLeft="30dp"
            android:layout_marginRight="5dp"

            android:layout_weight="1"
            android:gravity="center"
            android:text="反馈"
            android:textColor="#3774EF"
            app:shape="rectangle"
            app:shape_height="40dp"
            app:shape_radius="30dp"
            app:shape_solidColor="#ffffff"
            app:shape_strokeColor="#3774EF"
            app:shape_strokeWidth="1dp">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:drawablePadding="10dp"
                android:text="反馈"
                android:textColor="#3774EF" />

        </com.hjq.shape.layout.ShapeRelativeLayout>

        <com.hjq.shape.layout.ShapeRelativeLayout
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:layout_weight="1"
            android:gravity="center"
            android:textColor="#5DBF85"
            app:shape="rectangle"
            app:shape_height="40dp"
            app:shape_radius="30dp"
            app:shape_solidColor="#ffffff"
            app:shape_strokeColor="#5DBF85"
            app:shape_strokeWidth="1dp"
            android:layout_marginLeft="5dp"
            android:layout_marginRight="20dp">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:drawablePadding="10dp"
                android:text="反馈"
                android:textColor="#5DBF85" />

        </com.hjq.shape.layout.ShapeRelativeLayout>

    </LinearLayout>

</RelativeLayout>`
* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
* 小伙子，问题复现了，同时我也定位到了是关闭硬件加速导致的，但是很遗憾地告诉你，这个问题无解，因为如果不关闭硬件加速的情况下，在某些手机上面无法显示虚线和阴影。

```java
// 需要关闭硬件加速，否则虚线或者阴影在某些手机上面无法生效
view.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
```

**Comment by getActivity** [comment]
建议你的解决方案：
1. 使用 UI 切图来实现
2. 尝试使用别的阴影框架

**Comment by xiechunjiang** [comment]
好的，了解了，麻烦了
