### ISSUE TITLE
对于#56的问题的一个建议

### ISSUE THREAD

**Issue by po1xiao** [getActivity/ShapeView#57]
#### 建议收集

* issue 是否有人曾提过类似的问题？
提出过：https://github.com/getActivity/ShapeView/issues/56

* 框架文档是否有提及到此问题？
否

* 你觉得框架有什么不足之处？
对于这段代码
```
  public void intoBackground() {
        // 获取到的 Drawable 有可能为空
        Drawable drawable = buildBackgroundDrawable();
        // 需要关闭硬件加速，否则虚线或者阴影在某些手机上面无法生效
        if (isDashLineEnable() || isShadowEnable()) {
            mView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        }
        mView.setBackground(drawable);
    }
```
因为对虚线和阴影的适配会导致内容过长时在某些机器上无法显示，而且用户无法控制。
而且在LAYER_TYPE_SOFTWARE有些机型上边：Huawei P30 pro上（鸿蒙2.0系统），如果主题中加了
```
 <item name="android:forceDarkAllowed" tools:targetApi="q">true</item>
```
切换到暗黑模式时，有些界面颜色是无法转换的，这也是问题之一。

* 你觉得该怎么去完善会比较好？
是不是可以这样判断：
```
        if (mView.getLayerType() == View.LAYER_TYPE_NONE && (isDashLineEnable() || isShadowEnable())) {
            mView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        }
```
经过测试，如果用户不在代码中或者xml中设置LayerType，那么LayerType的类型就是View.LAYER_TYPE_NONE，使用者可以通过在xml中设置android:layerType="hardware"来做控制。对于哪些对阴影效果和虚线要求不是很严格的场景可是使用。毕竟有时候想用这个框架时，控件不显示是大问题，阴影和虚线效果可以退而求其次。并且这样写并不影响之前的默认行为，而且用户可以控制。

**Comment by getActivity** [comment]
小伙子，我来解答一下你的疑惑

控件不显示是个大问题，阴影和虚线不能显示是小问题：这种想法是对的，但是忘记考虑一个场景，控件不显示是必现的，而阴影和虚线不能显示不是必现的，那么这样就会导致一个问题，我在测试阶段明明是好的，怎么到了测试/线上就不行了呢？框架之所以坚持这样做，是为了效果统一，如果你觉得效果有问题，能够及时发现和处理，而不是到了测试/线上才发现，并且阴影和虚线不能显示在有些人看来不是小问题，而是大问题，没有办法退而求其次，产品才不会管这个框架在哪些机型能实现，在哪些机型又不行，大多数产品要的是，这种效果如果实现不了，就换一种效果来实现，宁可错杀不可放过。

**Comment by po1xiao** [comment]
其实测试过程中，控件不显示也不是必现的，用红米K50 Android13和魅族X8 Android8.0上是可以显示的，用两个其它三个测试机安卓版本华为P9 Android8.0和一款VIVO 6.0的真机及Win11的WSA上都显示不了，其它机器没测。

的确，如果说一些手机上可以显示阴影，有些手机上无法显示，严格来说是没有实现产品需求。其实我之所以会有这个建议，主要是因为这个行为是框架使用者可控的，让使用者决定是否可以接受这样的结果，如果不可接受就不增加android:layerType="hardware"配置，自己决定是换框架，还是和产品商量界面效果，比如说去掉阴影。

对于我司的产品来说，大概率验收是可以通过的，因为是个内部使用的办公app，用到的场景是一个功能属性很强，但是显示效果来说要求并非十分苛刻。

**Comment by po1xiao** [comment]
> 其实测试过程中，控件不显示也不是必现的，用红米K50 Android13和魅族X8 Android8.0上是可以显示的，用两个其它三个测试机安卓版本华为P9 Android8.0和一款VIVO 6.0的真机及Win11的WSA上都显示不了，其它机器没测。
> 
> 的确，如果说一些手机上可以显示阴影，有些手机上无法显示，严格来说是没有实现产品需求。其实我之所以会有这个建议，主要是因为这个行为是框架使用者可控的，让使用者决定是否可以接受这样的结果，如果不可接受就不增加android:layerType="hardware"配置，自己决定是换框架，还是和产品商量界面效果，比如说去掉阴影。
> 
> 对于我司的产品来说，大概率验收是可以通过的，因为是个内部使用的办公app，用到的场景是一个功能属性很强，但是显示效果来说要求并非十分苛刻，加上这个配置或者和产品商量一下都去掉阴影是可以的，但是有这个设置就有更多的主动性。

破案了，其实控件不显示某些条件下是必现的，只不过我的控件长度在一个临界范围内，正好前两个手机一屏能显示开，其它不能显示的都是因为一屏显示不开...
