### ISSUE TITLE
渐变色按钮的按压效果的疑问

### ISSUE THREAD

**Issue by Sun0630** [getActivity/ShapeView#58]
#### 问题描述

* 请描述一下你的疑惑【必填】：现在需求是按钮展示为一个渐变色，按压后(shape_solidPressedColor)效果同为渐变色，但是覆盖上有30%透明度的黑色，貌似无法实现这样的效果

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

**Comment by getActivity** [comment]
@Sun0630 小伙子，你如果想实现这个需求，使用 xml 属性肯定是实现不了的，但是你可以考虑直接在 java 代码中创建 `ShapeDrawable` 和 `StateListDrawable` 来实现。
