### ISSUE TITLE
ShapeView在列表中使用，有频繁创建Drawable问题

### ISSUE THREAD

**Issue by lysung** [getActivity/ShapeView#59]
#### 问题描述
有一个列表，使用了ShapeButton，在根据下发的不同颜色，需要设置成不同的背景颜色。

而在通过builder设置完颜色之后，需要调用 intoBackground()。这种方式，当列表快速滑动时，会存在频繁重新创建Drawable对象问题。

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）
否
* 框架文档是否有提及到此问题？【必答】：是/否（请先看完框架的文档后再来提建议）
否

**Comment by getActivity** [comment]
小伙子，你用的是框架最新的版本？

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
