### ISSUE TITLE
2.2版本升到3.0版本，没有修改任何配置，效果全没了

### ISSUE THREAD

**Issue by lhdmady** [getActivity/ShapeView#6]
![image](https://user-images.githubusercontent.com/25815331/127802825-a8d41d2c-2a97-4ac1-8961-be1489695345.png)
![image](https://user-images.githubusercontent.com/25815331/127802999-3f3a6e79-cda6-4a00-aee2-306f70e3093f.png)

<com.hjq.shape.view.ShapeEditText
        android:id="@+id/etEmail"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_marginHorizontal="40dp"
        android:gravity="center_vertical"
        android:hint="邮箱"
        android:inputType="textEmailAddress"
        android:paddingHorizontal="10dp"
        app:layout_constraintTop_toTopOf="parent"
        app:shape_solidColor="#ffffff"
        app:shape_strokeColor="#000000"
        app:shape_strokeWidth="1dp" />

**Comment by getActivity** [comment]
小伙子，问题已经修复了，更新到 3.2 版本即可。
