### ISSUE TITLE
添加背景模糊效果

### ISSUE THREAD

**Issue by Lans** [getActivity/ShapeView#60]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）否

* 框架文档是否有提及到此问题？【必答】：是/否（请先看完框架的文档后再来提建议）否

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）添加背景模糊效果

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）使用RenderScript实现

**Comment by getActivity** [comment]
多谢小伙子建议，我会慎重考虑一下。

**Comment by getActivity** [comment]
小伙子，我在调研这个需求，目前发现用 ShapeView 是实现的不了，这是因为毛玻璃特效的实现原理是需要先拿到背景的 Bitmap 的，然后对背景的 Bitmap 进行特殊处理并设置到 View 背景上面，而 ShapeView 只知道当前 View 背景，不能知道它外层的背景是什么样的，建议你采用其他方式来实现，例如 Glide 框架，或者其他毛玻璃的库。
