### ISSUE TITLE
startColor endColor angle不能设置其他的状态（selected、checked....），建议添加

### ISSUE THREAD

**Issue by ozy1996** [getActivity/ShapeView#61]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】startColor endColor angle不能设置其他的状态（selected、checked....），建议添加

* 你觉得该怎么去完善会比较好？【非必答】

**Comment by getActivity** [comment]
https://github.com/getActivity/ShapeView/issues/58
