### ISSUE TITLE
ShapeCheckBox 能添加shape_buttonSelectedDrawable 他的方向吗，现在默认是在左边的

### ISSUE THREAD

**Issue by Lans** [getActivity/ShapeView#62]
#### 问题描述

* 请描述一下你的疑惑【必填】：XXX（注意：如果是框架 bug 请不要在这里提，否则一概不受理）
* 
ShapeCheckBox 能添加shape_buttonSelectedDrawable 他的方向吗，现在默认是在左边的，因为ShapeCheckBox做单个控制开关类型的做开关很好用。比如这种图
![image](https://user-images.githubusercontent.com/16605722/227428161-df1cce61-ce8e-4946-bf3a-7a488f5848aa.png)

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）否

* 框架文档是否有提及到此问题？【必答】：是/否（请先看完框架的文档后再来提建议）否

**Comment by getActivity** [comment]
小伙子，如果是基于 CheckBox 改造，那么是实现不了的，具体为什么不行，你可以看一下 CheckBox 绘制图标的源码实现就知道了
