### ISSUE TITLE
ShapeTextView添加background会不显示

### ISSUE THREAD

**Issue by Lans** [getActivity/ShapeView#63]
#### 问题描述

* 请描述一下你的疑惑【必填】：XXX（注意：如果是框架 bug 请不要在这里提，否则一概不受理）
*  <com.hjq.shape.view.ShapeTextView
                android:id="@+id/leftSvgBgImg"
                android:layout_width="0dp"
                android:layout_height="205dp"
                android:background="@drawable/ic_bg"
                app:layout_constraintBottom_toBottomOf="@id/rightBgImg"
                app:layout_constraintEnd_toStartOf="@id/rightBgImg"
                app:layout_constraintHorizontal_weight="1"
                app:layout_constraintStart_toStartOf="@id/timeBg"
                app:layout_constraintTop_toTopOf="@id/rightBgImg" />

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）否

* 框架文档是否有提及到此问题？【必答】：是/否（请先看完框架的文档后再来提建议）否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
