### ISSUE TITLE
ShapeTextView阴影效果无法预览吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/ShapeView#64]
#### 问题描述

加入以下两行阴影的代码就没法预览效果了，as预览页面上不显示，不知道为什么

````
app:shape_shadowColor
app:shape_shadowSize
````
#### 请回答

* issue 是否有人曾提过类似的问题？【必答】 无

* 框架文档是否有提及到此问题？【必答】：否

**Comment by SaltedFish-Extreme** [comment]
😥最新版的as上无法预览阴影效果，不知道是啥原因，加入阴影部分的代码会导致预览页面上不显示控件

**Comment by getActivity** [comment]
<img width="440" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/dd166690-9d8e-4a1d-b425-9ebdc23ea00b">

**Comment by SaltedFish-Extreme** [comment]
不应该啊，我是用的最新版的，就不显示😂直接复制代码都不行

![image](https://github.com/getActivity/ShapeView/assets/54784104/186f157b-9ba2-47c9-8522-f1c597841f74)

![image](https://github.com/getActivity/ShapeView/assets/54784104/8a0e26e2-7a7b-4358-91cb-bc46fb175c4a)

**Comment by SaltedFish-Extreme** [comment]
gradle用7.4和8.0版本都是这样，不知道什么问题，不知道其他人有没有这个情况

**Comment by SaltedFish-Extreme** [comment]
运行代码倒是没问题，阴影正常显示😂

**Comment by SaltedFish-Extreme** [comment]
好吧😥
