### ISSUE TITLE
库很好用，能否给所有带getShapeDrawableBuilder()方法的view统一实现一个接口IShapeView

### ISSUE THREAD

**Issue by mtzqc** [getActivity/ShapeView#65]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】：挺好的

提供一个统一的父接口
![image](https://github.com/getActivity/ShapeView/assets/29159362/3442b038-d979-4aaf-9892-5ace4a298125)
好处是方便统一封装base，如ViewHolder对shape的处理，
从框架上来看，封装的程度更高，新手也可以快速的点击IShapeView查看对应的子类，查看库提供类哪些Shape的View

感谢轮子哥开源的库，ShapeView，XXPermissions，TitleBar用起来很不错，节约了大部分开发时间

**Comment by getActivity** [comment]
收到，多谢小伙子的建议，会在下个版本加上，后续留意下版本更新。
