### ISSUE TITLE
代码动态修改边框颜色，夜间模式不起效果

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/ShapeView#66]
#### 问题描述

* 框架版本【必填】：8.5

* 问题描述【必填】：代码动态修改边框颜色，夜间模式不起效果

* 复现步骤【必填】：
````kotlin
when (AppApplication.context.resources.configuration.uiMode.and(Configuration.UI_MODE_NIGHT_MASK)) {
            Configuration.UI_MODE_NIGHT_YES -> {
                AppConfig.DarkTheme = true
            }

            Configuration.UI_MODE_NIGHT_NO -> {
                AppConfig.DarkTheme = false
            }

            Configuration.UI_MODE_NIGHT_UNDEFINED -> {
                AppConfig.DarkTheme = false
            }
        }
````
````kotlin
//动态修改边框默认颜色及按下时颜色
            shapeDrawableBuilder.apply {
                strokeColor = randomColor()
                strokePressedColor = if (AppConfig.DarkTheme) {
                    R.color.white
                } else {
                    R.color.black
                }
                intoBackground()
            }
````
或者设置的颜色在res\value-night\colors.xml中配置过，切换手机夜间主题/暗色模式，也不会自动使用夜间模式的颜色
* 是否必现【必填】：是

* 出现问题的手机信息【必填】：一加七Pro

* 出现问题的安卓版本【必填】：11

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：当前手机

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，劳烦提供一个可供复现的 Demo 工程，我要对问题进行复现。

**Comment by SaltedFish-Extreme** [comment]
我在你项目上改的，但是压缩后太大了，就两个文件，你复制到你这个项目上试试吧😂我直接在代码里修改边框颜色都没反应了

[Downloads.zip](https://github.com/getActivity/ShapeView/files/11661507/Downloads.zip)

**Comment by SaltedFish-Extreme** [comment]
Android Studio上显示边框，手机上都不显示了😂

**Comment by SaltedFish-Extreme** [comment]
边框和填充色都不显示了😂
