### ISSUE TITLE
ShapeEditText点击事件的问题

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/ShapeView#67]
#### 问题描述

* 请描述一下你的疑惑【必填】：左右图标的点击事件应该怎么写😂这个好像没有扩展啊，比如我用`drawableEnd`设置一个图标，这个图标的点击事件不知道应该怎么设置😥

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】 无（一旦出现重复提问我将不会再次解答）

* 框架文档是否有提及到此问题？【必答】：否（请先看完框架的文档后再来提建议）

**Comment by getActivity** [comment]
小伙子，你确定这个问题是框架的问题？

**Comment by SaltedFish-Extreme** [comment]
不是问题啊，只是疑问和建议😂要是能设置左右两侧图标的点击事件就好了🤔

**Comment by getActivity** [comment]
小伙子，系统没有开放这类 API，框架也不会考虑实现，建议你通过组合多个 View 来实现。

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，系统没有开放这类 API，框架也不会考虑实现，建议你通过组合多个 View 来实现。

那好吧😥
