### ISSUE TITLE
8.5版本在Adapter里动态设置默认填充背景和选择填充背景失效，只显示默认填充背景和边框，选择背景无效

### ISSUE THREAD

**Issue by hhh5022456** [getActivity/ShapeView#68]
#### 问题描述

* 请描述一下你的疑惑【必填】：8.5版本动态设置默认填充背景和选择填充背景失效，只显示默认填充背景和边框，选择背景无效

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】没有

* 框架文档是否有提及到此问题？【必答】：否

    inner class ButtonViewHolder(view: View) : RecyclerView.ViewHolder(view) {
        private val shapeButton: ShapeButton  = view.findViewById(R.id.button)
        fun bind(item: Int) {
            shapeButton.text = item.toString()
            shapeButton.isSelected = true
            shapeButton.setOnClickListener { onClick(item) }

            shapeButton.shapeDrawableBuilder
                .setSolidSelectedColor(R.color.color_AEC0EF)//选择状态填充
                .setSolidColor(R.color.color_878FA4)//填充色默认
                .setStrokeColor(R.color.color_455580)//边框色默认
                .setStrokeWidth(1)
                .setStrokeSelectedColor(R.color.color_235BED)//选择状态边框
                .intoBackground()

            shapeButton.textColorBuilder
                .setTextColor(R.color.color_535A66)
                .setTextSelectedColor(R.color.color_235BED)
                .intoTextColor()

            shapeButton.text = "改变"
            Log.e("HomeGridPopAdapter", "${shapeButton.isSelected.toString()}")
        }
    }

    <com.hjq.shape.view.ShapeButton
        android:id="@+id/button"
        android:layout_width="@dimen/p140"
        android:layout_height="@dimen/p240"
        android:layout_margin="@dimen/p40"
        android:gravity="center"
        android:text="01"
        android:textSize="@dimen/p60"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:shape="rectangle"
        app:shape_radius="3dp"
        />

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
