### ISSUE TITLE
ShapeTextView设置文本水平渐变或垂直渐变效果后，文本不能显示多行。

### ISSUE THREAD

**Issue by haoguibao** [getActivity/ShapeView#69]
#### 问题描述

* 框架版本【必填】8.5

* 问题描述【必填】：ShapeTextView设置文本水平渐变（app:shape_textGradientOrientation="horizontal"）或垂直渐变效果后，文本不能显示多行，只能显示一行，超出宽度的文本显示不全。

* 复现步骤【必填】：           
               <com.hjq.shape.view.ShapeTextView
                android:layout_width="150dp"
                android:layout_height="wrap_content"
                android:layout_margin="10dp"
                android:gravity="center"
                android:padding="10dp"
                android:text="文本水平渐变效果文本水平渐变效果文本水平渐变效果文本水平渐变效果文本水平渐变效果文本水平渐变效果文本水平渐变效果"
                android:textSize="18sp"
                app:shape_textEndColor="#ED58FF"
                app:shape_textGradientOrientation="horizontal"
                app:shape_textStartColor="#49DAFA" />

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：测试出现的手机有OPPO K7s，vivo Y70t，华为 Mate40等。

* 出现问题的安卓版本【必填】：Android10，Android12。

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 shape.xml 来实现是否也会出现该问题【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，我试过了，确实会存在这个问题，但是遗憾地告知你，这个问题无法修复，这是因为目前文本颜色渐变色使用的是 继承 ReplacementSpan 类的实现方案，这个类里面有一个 `getSize` 方法，要求实现者返回测量文本的宽度，除此之外没有提供任何方法返回或者设置测量文本的高度，系统默认就是给单行的高度来显示，所以我无法实现多行的情况下还能渐变色。

**Comment by getActivity** [comment]
* 但也不是没有其他办法，你可以考虑使用以下方式来实现多行文本渐变色

```java
public class GradientTextView extends AppCompatTextView {

    @Override
    protected void onDraw(Canvas canvas) {
        LinearGradient linearGradient = new LinearGradient(0, 0, 0 + getMeasuredWidth(), 0,
                new int[]{0xFF49DAFA, 0xFFED58FF}, null, Shader.TileMode.REPEAT);
        getPaint().setShader(linearGradient);
        super.onDraw(canvas);
    }
}
```

**Comment by haoguibao** [comment]
> * 但也不是没有其他办法，你可以考虑使用以下方式来实现多行文本渐变色
> 
> 
> ```java
> public class GradientTextView extends AppCompatTextView {
> 
>     @Override
>     protected void onDraw(Canvas canvas) {
>         LinearGradient linearGradient = new LinearGradient(0, 0, getWidth(), 0,
>                 new int[]{0xFF49DAFA, 0xFFED58FF}, null, Shader.TileMode.REPEAT);
>         getPaint().setShader(linearGradient);
>         super.onDraw(canvas);
>     }
> }
> ```

感谢轮子哥的回复，这种方式我提Issues前已经试过了，可以设置文本渐变色并且支持多行文本。
当时想着ShapeTextView是否也支持多行文本的文字渐变色，所以冒昧提了这个issues，看看是否是我对ShapeTextView的使用不当或其它原因导致的不能多行文本渐变。再次谢谢轮子哥。
