### ISSUE TITLE
[Bug]：框架版本8.5升级到9.0，项目构建失败

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/ShapeView#70]
### 框架版本【必填】

9.0

### 问题描述【必填】

Android resource linking failed
com.example.smile.app-mergeDebugResources-2:/values/values.xml:6519: error: style attribute 'attr/shape (aka com.example.smile:attr/shape)' not found.
error: failed linking references.

### 复现步骤【必填】

框架版本升级，构建项目失败

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

1+7P

### 出现问题的安卓版本【必填】

11

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

是

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
Android resource linking failed
com.example.smile.app-mergeDebugResources-2:/values/values.xml:6519: error: style attribute 'attr/shape (aka com.example.smile:attr/shape)' not found.
error: failed linking references.
```

**Comment by SaltedFish-Extreme** [comment]
不兼容升级，应该标注一下，属性变了，比如`app:shape="rectangle"`属性变成了`app:shape_type="rectangle"`，`shape_strokeWidth`属性没了，换成`shape_strokeSize`，把这两个地方改了之后还是构建失败

**Comment by getActivity** [comment]
<img width="886" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/67377aad-ec67-47b6-a0c0-5cd00606065d">

**Comment by getActivity** [comment]
<img width="886" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/67377aad-ec67-47b6-a0c0-5cd00606065d">

**Comment by SaltedFish-Extreme** [comment]
对，我后来往下翻看到了，说实话这个在中间，字也小，不显眼，应该放在最上面，字再大一点

我替换之后，还是构建失败，出现上面那个错误，不知道什么原因

**Comment by getActivity** [comment]
@SaltedFish-Extreme 小伙子，你应该是还有一些属性没有适配到位，所以才会编译不过去。

**Comment by SaltedFish-Extreme** [comment]
> @SaltedFish-Extreme 小伙子，你应该是还有一些属性没有适配到位，所以才会编译不过去。

不应该啊，一共就用到了三个属性，as的xml布局预览都显示正常，就是编译过不去，清除缓存也不行😂

**Comment by SaltedFish-Extreme** [comment]
好了，好像是一个style里面的shape属性没改，我挨个查发现了，as没提示😂这次编译成功了
