### ISSUE TITLE
[Question]:

### ISSUE THREAD

**Issue by lhjgege** [getActivity/ShapeView#71]
### Question Description [Required]

新版9.0的版本依赖ShapeLinearLayout预览不会显示出来
![image](https://github.com/getActivity/ShapeView/assets/20966610/5733beff-1d72-4c8c-a912-90a49ff78ee9)

### Is the issue mentioned in the framework documentation? [Required]

Not Selected

### Did you consult the framework documentation but couldn't find a solution? [Required]

Not Selected

### Has a similar issue been reported in the issue list? [Required]

Not Selected

### Have you searched the issue list but couldn't find a solution? [Required]

Not Selected

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
