### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by mosentest** [getActivity/ShapeView#72]
### Framework Version [Required]

33

### Issue Description [Required]

9.0版本没办法预览

### Steps to Reproduce [Required]

1

### Is the Issue Reproducible? [Required]

Not Selected

### Project targetSdkVersion [Required]

33

### Device Information [Required]

33

### Android Version [Required]

33

### Is it specific to certain device models? [Required]

33

### Does the latest version of the framework have this issue? [Required]

Yes

### Is the issue mentioned in the framework documentation? [Required]

Yes

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

Yes

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

### Can the issue be reproduced with a demo project? [Required]

Yes

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
