### ISSUE TITLE
[Bug]：布局无法预览

### ISSUE THREAD

**Issue by tryedhp** [getActivity/ShapeView#74]
### 框架版本【必填】

ShapeDrawable:3.0

### 问题描述【必填】

设置阴影效果后无法预览

### 复现步骤【必填】

使用ShapeLinearLayout设置shape_shadowSize属性后子view都预览不了了

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

28

### 出现问题的手机信息【必填】

Android studio  2022.3.1

### 出现问题的安卓版本【必填】

Android studio  2022.3.1

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

都会

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 乱填 issue 问题

请重新提一个 issue 并纠正以上问题

**Comment by SaltedFish-Extreme** [comment]
轮子哥打回的issues太多了吧😂设置阴影后无法预览的问题，我很久就提过了，一直没改，可能是新版AS的问题，导致预览页面无法显示设置了阴影的控件，也不知道到底是啥问题，轮子哥每次都打回，issues的模板太多了，这不是折磨人嘛😂好不容易填完了，结果给打回了，这个冷冰冰的态度有点不像是轮子哥了😂

**Comment by getActivity** [comment]
https://github.com/getActivity/ShapeView/issues/64

**Comment by getActivity** [comment]
@SaltedFish-Extreme 小伙子，你表面看到我的是冷冰冰的态度，但是殊不知我在维护规则付出努力，假设每个人都为所欲为地提 issue，别人提过的也要提，文档上面写了也要提，这些多出来的工作量，就算来十个轮子哥也不够用，你为这些被打回的 issue 打抱不平，那谁为轮子哥重复劳动打抱不平呢？我一旦定了这个规则，就必须要严格遵守它，谁都来不好使，如果每个人都可以随意践踏规则，那规则就形同虚设，还要规则干什么呢？

**Comment by SaltedFish-Extreme** [comment]
@getActivity 也是，轮子哥为了框架维护尽心尽力了，确实按照规则提issues能减少开发者理解bug的难度，过滤掉重复和不是bug的问题，提高维护效率😂但是我还是没有理解这个`乱填 issue 问题`，感觉好几个被打回的都是这句😂重新提一个issues既费时也费力，可能很多个人开发者就不再回复了😂

**Comment by getActivity** [comment]
@SaltedFish-Extreme 乱填 issue 问题就是有的说成没的，例如：《框架文档是否提及了该问题》，明明文档上面写了，但是有的人也没有看过文档，直接填《否》，只顾自己省事，其他一概不管。

**Comment by SaltedFish-Extreme** [comment]
好吧😂
