### ISSUE TITLE
[Bug]：ShapeImageView设置了app:shape_radius，同时设置android:scaleType="centerCrop"，圆角无效

### ISSUE THREAD

**Issue by candebbs** [getActivity/ShapeView#75]
### 框架版本【必填】

9.0

### 问题描述【必填】

如题，不知道其它的android:scaleType属性会不会这样。

### 复现步骤【必填】

        <com.hjq.shape.view.ShapeImageView
            android:layout_width="@dimen/dp_320"
            android:layout_height="@dimen/dp_240"
            android:layout_marginVertical="@dimen/dp_40"
            android:scaleType="centerCrop"
            android:src="@drawable/read_idcard"
            app:shape_radius="@dimen/dp_60" />

就是这样设置，就不显示圆角。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

31

### 出现问题的手机信息【必填】

readme x2 pro

### 出现问题的安卓版本【必填】

11

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

readme

### 框架最新的版本是否存在这个问题【必答】

未选择

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 乱填 issue 问题

* 没有严格按照 issue 模板填写

请重新提一个 issue 并纠正以上问题
