### ISSUE TITLE
ShapeConstraintLayout没阴影

### ISSUE THREAD

**Issue by GuoLiangjun123** [getActivity/ShapeView#76]
### 框架版本【必填】

9.0

### 问题描述【必填】

xml中使用ShapeConstraintLayout时并没有阴影效果

### 复现步骤【必填】

    <com.hjq.shape.layout.ShapeConstraintLayout
        android:id="@+id/cl1"
        android:layout_width="0dp"
        android:layout_height="50dp"
        app:layout_constraintLeft_toLeftOf="parent"
        android:layout_marginLeft="@dimen/dp_15"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginRight="@dimen/dp_15"
        app:layout_constraintTop_toBottomOf="@+id/ivLeft"
        android:layout_marginTop="@dimen/dp_12"
        app:shape_shadowSize="@dimen/dp_10"
        app:shape_shadowColor="#2e000000"
        app:shape_radius="@dimen/dp_20">

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

小米10

### 出现问题的安卓版本【必填】

13

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，请先回答我如下问题

<img width="449" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/bc64d86b-496f-4241-bf13-ff0b70e94919">

**Comment by GuoLiangjun123** [comment]
> 小伙子，请重新回答该问题（要求必须看过）
> 
> <img alt="image" width="449" src="https://private-user-images.githubusercontent.com/28616817/286257452-bc64d86b-496f-4241-bf13-ff0b70e94919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjQ0MTQsIm5iZiI6MTcwMTIyNDExNCwicGF0aCI6Ii8yODYxNjgxNy8yODYyNTc0NTItYmM2NGQ4NmItNDk2Zi00MjQxLWJmMTMtZmYwYjcwZTk0OTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAyMTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOWViMWIyMjhkMjkwNjNjZGVkN2M3Y2NkYjgwN2U3NWY3MmFkMGU2YTZiMDY0M2JkMzdlZjIxYzNjNzg0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1Sz1AjPhkj6PwlUIZmoQrOFmNEk4JgaGlXPKq9UyZsM">

是的，我看了issue列表，依然没能解决

**Comment by getActivity** [comment]
小伙子，你这个问题是因为没有设置充填色导致的，设置一下填充色即可。
