### ISSUE TITLE
[建议]：可否支持一下RTL 布局

### ISSUE THREAD

**Issue by nbwzlyd** [getActivity/ShapeView#77]
### 你觉得框架有什么不足之处？【必答】

框架很好，但是在适配阿拉伯国家的一些布局时，left right就不适用 了，可否支持一下start end?

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
[ShapeView-9.2.aar.zip](https://github.com/getActivity/ShapeView/files/13534391/ShapeView-9.2.aar.zip)

**Comment by getActivity** [comment]
@nbwzlyd 小伙子，针对你提出的建议，新增了  `shape_radiusInTopStart`、`shape_radiusInTopEnd`、`shape_radiusInBottomStart`、`shape_radiusInBottomEnd` 这几个属性，你可以下载上面的 aar 包进行测试。

**Comment by nbwzlyd** [comment]
感谢
