### ISSUE TITLE
[建议]：ShapeImageView 是否可以 支持裁剪？

### ISSUE THREAD

**Issue by houkhan** [getActivity/ShapeView#79]
### 你觉得框架有什么不足之处？【必答】

ShapeImageView 当设置 shape_type 或者 shape_radius 是 设置图片不会裁剪（设置图片依然是图片原来的样子）

我的理解是 既然用到了 ShapeImageView 应该是需要 裁剪图片的（圆角 或者 圆形） 不然 不会使用到 ShapeImageView 

当前的 ShapeImageView 感觉 这样设计 是没有 使用的必要的 满足图片裁剪 这个还是很重要的

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

我觉得可以当  ShapeImageView 设置了 shape_radius/shape_type后 在预览时 我使用 tools:shape_solidColor="@color/color_main" 看到的是什么形状 当我代码设置了图片的drawable运行起来就是什么样子

**Comment by getActivity** [comment]
小伙子，这个问题你确定文档上面没有写？

**Comment by houkhan** [comment]
不好意思 我把这个关闭了
