### ISSUE TITLE
[疑惑]：运行ShapeView源码，填充色渐变与边框渐变，设置斜角GradientOrientation效果错误。

### ISSUE THREAD

**Issue by shuimuqinghua** [getActivity/ShapeView#80]
### 问题描述【必填】

1. 下载ShapeView源码，成功运行。
2. 改变ShapeButton边框色渐变效果，设置shape_strokeGradientOrientation为topLeftToBottomRight
3. 运行，结果渐变仍旧是从上到下。如图1
4. 改变ShapeButton填充渐变色，设置shape_solidGradientOrientation为bottomRightToTopLeft，效果显示为从右往左渐变。如图2
<img width="1481" alt="image" src="https://github.com/getActivity/ShapeView/assets/7427087/0d4ec7e4-996b-41ff-8801-30fd3fdfed6c">
<img width="1498" alt="image" src="https://github.com/getActivity/ShapeView/assets/7427087/735358fa-ed18-4b3a-b9dc-a318b1c144a7">

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="1260" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/f422cb22-5292-4415-8d20-b3c84a2d726c">

<img width="1256" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/ce9028ac-daab-44bd-b5ac-608a093ca21b">

---

<img width="1253" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/29b2c288-3432-4cc8-ad78-28b70a7283ae">

<img width="1252" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/a1c02e81-ffb4-44a7-916d-0fddf562b61c">

**Comment by shuimuqinghua** [comment]
好的，感谢解答。
