### ISSUE TITLE
[建议]：能否依赖Android X依赖,而不是依赖support

### ISSUE THREAD

**Issue by lydlovezjr** [getActivity/ShapeView#81]
### 你觉得框架有什么不足之处？【必答】

能否依赖Android X依赖,而不是依赖support

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

**Comment by getActivity** [comment]
https://github.com/getActivity/ShapeView/issues/52

**Comment by getActivity** [comment]
https://github.com/getActivity/ShapeView/issues/31
