### ISSUE TITLE
[Suggestion]:希望可以增加状态下的drawable设置

### ISSUE THREAD

**Issue by EmccK** [getActivity/ShapeView#82]
### What are the shortcomings you have noticed in the framework? [Required]

没办法设置不同状态下的drawable
例如selected,pressed下的drawable

### Has a similar suggestion been made in the issue list? [Required]

No

### Is the suggestion mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### How do you suggest improving it? [Optional]

像`shapeTextView`里面的`shape_textSelectedColor`一样，添加`shape_selectedDrawable`，以及其他的设置

**Comment by getActivity** [comment]
小伙子，你说的设置不同状态下的 drawable 是设置给哪里？控件的背景？

**Comment by EmccK** [comment]
是的，就是不同状态下的背景图片，例如正常，选中，按压等状态下的背景

**Comment by getActivity** [comment]
小伙子，经过认真斟酌，这个建议将不会被采纳，具体原因是 View 背景跟随选中、按压的情况下修改图片的场景比较罕见，如果要实现这一功能，会增加很多代码行数及逻辑判断，综合考虑下来实现这个功能点的价值和意义不是很大。

**Comment by EmccK** [comment]
<img width="53" alt="image" src="https://github.com/getActivity/ShapeView/assets/34116538/6f106801-a344-459a-936b-e45319f55113">
<img width="58" alt="image" src="https://github.com/getActivity/ShapeView/assets/34116538/fb6f6883-e337-41f4-baba-dcd3107f5c04">
那这种情况下的需求，怎么使用这个框架实现呢？
如果添加了shape_selectedDrawable，我就可以只用设置isSelected字段就行了

**Comment by getActivity** [comment]
<img width="853" alt="image" src="https://github.com/getActivity/ShapeView/assets/28616817/c7225b30-7832-4820-a2ad-1f9abd1f4b01">

**Comment by getActivity** [comment]
@EmccK 如果是针对 CheckBox 或者 RadioButton 控件的，框架有对外提供这几个属性，我都有写在文档上面。

**Comment by EmccK** [comment]
```
<com.hjq.shape.view.ShapeCheckBox
    android:id="@+id/iv_star"
    android:layout_width="wrap_content"
    android:layout_height="20dp"
    android:background="@null"
    android:gravity="center_vertical"
    android:textSize="11sp"
    app:shape_buttonDrawable="@drawable/ic_star_unselected"
    app:shape_buttonSelectedDrawable="@drawable/ic_star_selected"
    app:shape_textColor="@color/text_color_3"
    app:shape_textSelectedColor="@color/normal_red_color"
    tools:text="029" />
```

但是这两种控件如果我设置的是图片，图片大小比控件大的话，就只会显示出一部分
RaidoButton也是一样的问题
<img width="105" alt="image" src="https://github.com/getActivity/ShapeView/assets/34116538/e9fa6a73-5f43-4207-8a5c-7451d9004309">

**Comment by getActivity** [comment]
@EmccK 小伙子，很抱歉，我现在才看到你的回复，如果这种情况我建议你将图片从位图变成矢量图，这样就不会有这样的问题。

**Comment by aacai** [comment]
作者大大,可不可以把这个框架完全迁移到androidx,引入这个框架目前需要support库,不是很好

**Comment by getActivity** [comment]
@aacai 小伙子，你这个问题别人已经问过了，具体可以到 issue 列表中查找，我就不重复解答了。

**Comment by aacai** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by aacai** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
