### ISSUE TITLE
[疑惑]：如何利用shapeView绘制垂直方向的虚线  不知道框架是否有实现这个功能

### ISSUE THREAD

**Issue by daquanzheng** [getActivity/ShapeView#83]
### 问题描述【必填】

想通过shapeView绘制垂直方向的虚线 试了几次未能实现 设置shape_type=line时 没有方法设置其方向

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你确定框架文档上面没有写？

**Comment by daquanzheng** [comment]
> 小伙子，你确定框架文档上面没有写？

本想用您的框架来实现垂直方向的虚线绘制，但确实没有找到对应的方式，如果有方法实现，还望作者大方告知下。谢谢啦。

**Comment by getActivity** [comment]
用 `app:shape_lineGravity="left"` 或者 `app:shape_lineGravity="right"` 属性可以实现

**Comment by daquanzheng** [comment]
> 用 `app:shape_lineGravity="left"` 或者 `app:shape_lineGravity="right"` 属性可以实现

确实可以实现 谢谢！可能之前没有预览效果 我没有试着用这两个值，只试了一下center的值，发现不行才来提问的。您的框架很好用，作者您辛苦了。
