### ISSUE TITLE
[建议]：

### ISSUE THREAD

**Issue by ZhangBingbin** [getActivity/ShapeView#87]
### 你觉得框架有什么不足之处？【必答】

框架很好

### issue 是否有人曾提过类似的建议？【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

对于rtl布局不能适配，issue中提供的aar依赖后运行会出现崩溃

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
