### ISSUE TITLE
[疑惑]：9.0版本的仓库怎么找不到了

### ISSUE THREAD

**Issue by qwwuyu** [getActivity/ShapeView#89]
### 问题描述【必填】

https://jitpack.io/com/github/getActivity/ShapeView/ 在版本列表里可以看到包含9.0
https://jitpack.io/com/github/getActivity/ShapeView/9.2/ 可以正常预览
https://jitpack.io/com/github/getActivity/ShapeView/9.0 找不到该文件

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

<img width="397" alt="image" src="https://github.com/user-attachments/assets/8ebb6f4a-c63b-4df0-818d-95f87d7d585f">

* 需要查阅文档后，确认没有人提过类似的问题，再提 issue

请重新提一个 issue 并纠正以上问题

**Comment by qwwuyu** [comment]
> 小伙子，该 issue 被打回，打回的原因如下：
> 
> <img alt="image" width="397" src="https://private-user-images.githubusercontent.com/28616817/353141005-8ebb6f4a-c63b-4df0-818d-95f87d7d585f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTM1MTAsIm5iZiI6MTcyMjQ5MzIxMCwicGF0aCI6Ii8yODYxNjgxNy8zNTMxNDEwMDUtOGViYjZmNGEtYzYzYi00ZGYwLTgxOGQtOTVmODdkN2Q1ODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0N2FmM2FiMzUwZGVmMzI3NjVkZDk5YTQ1NzZiZWQ3OTBiMjBlNGQ3NmU3ZGY2NTNmNWYwYzg1M2Q1M2Y1ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OcRYDitQWefVGcI67A33r_AY0xp8POKVe65FBHCN6Ws">
> * 需要查阅文档后，确认没有人提过类似的问题，再提 issue
> 
> 请重新提一个 issue 并纠正以上问题

```是否已经查阅框架文档但还未能解决的```
语言文件绕进去了,我查阅了并解决了,只是有疑问,所以写了否....
