### ISSUE TITLE
多级嵌套后不显示

### ISSUE THREAD

**Issue by GTX-GSO** [getActivity/ShapeView#9]
![微信截图_20210831110549](https://user-images.githubusercontent.com/54223273/131435781-de8ff255-9ea0-4f2b-97d2-e903122569fd.png)
嵌套层级如下  :（
![微信截图_20210831111325](https://user-images.githubusercontent.com/54223273/131435793-d2ba949c-cd54-4c73-b512-60e1aad31cbf.png)

**Comment by getActivity** [comment]
小伙子，不使用框架中的 View，而是换成原生的 View 是否还有这样的问题？

**Comment by GTX-GSO** [comment]
大伙汁，是AS的bug，重写了一遍显示正常了，你的轮子很棒！
