### ISSUE TITLE
[疑惑]：ShapeTextView设置为ShapeType.OVAL，背景图片还是显示矩形

### ISSUE THREAD

**Issue by yecaler** [getActivity/ShapeView#90]
### 问题描述【必填】

textview.shapeDrawableBuilder.type = ShapeType.OVAL

stateListDrawable.addState(intArrayOf(), drawable2)
背景图片还是显示矩形，应该显示椭圆的，需要如何配置？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
框架不能裁剪图片，不能裁剪图片，不能裁剪图片

**Comment by getActivity** [comment]
框架只能对自己内部生产的 Drawable 对象进行裁剪

**Comment by yecaler** [comment]
明白了，感谢大佬
