### ISSUE TITLE
[疑惑]：ShapeLinearLayout 设置shape_radius圆角后，子view没有被裁剪

### ISSUE THREAD

**Issue by wanghao890109** [getActivity/ShapeView#91]
### 问题描述【必填】

ShapeLinearLayout 设置shape_radius圆角后，如果子view撑满容器且有背景颜色。效果上看不到这个圆角效果

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题：看似回答了问题，但是实际是乱回答，没有认真去核实问题就乱回答

请重新提一个 issue 并纠正以上问题
