### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by lhjgege** [getActivity/ShapeView#93]
### 框架版本【必填】

9.2

### 问题描述【必填】

在代码中设置色显示的颜色和实际不符合

### 复现步骤【必填】

在代码中通过一下设置颜色在手机显示出来的颜色和实际颜色不符合
![image](https://github.com/user-attachments/assets/d2496a8f-f812-405f-9f8c-bf58e34cf50e)

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

红米 note9

### 出现问题的安卓版本【必填】

android 12

### 是部分机型还是所有机型都会出现【必答】

所有机型

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

### 提供报错堆栈

```text
为报错
```

### 提供截图或视频

![image](https://github.com/user-attachments/assets/d4062c0e-26ef-4eb1-9df3-555b3e82fbed)

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写
