### ISSUE TITLE
在最新的AS版本中 无法依赖 ShapeView-9.2

### ISSUE THREAD

**Issue by everyline** [getActivity/ShapeView#94]
### Question Description [Required]

![图片](https://github.com/user-attachments/assets/2aceaa59-b03f-4d96-a26e-849725b65ea4)

### Is the issue mentioned in the framework documentation? [Required]

Not Selected

### Did you consult the framework documentation but couldn't find a solution? [Required]

Not Selected

### Has a similar issue been reported in the issue list? [Required]

Not Selected

### Have you searched the issue list but couldn't find a solution? [Required]

Not Selected

**Comment by yuanbaoyang** [comment]
+1

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写
