### ISSUE TITLE
[建议]：增加 shape_shadowShowSide

### ISSUE THREAD

**Issue by actor20170211030627** [getActivity/ShapeView#97]
### 你觉得框架有什么不足之处？【必答】

<pre>
&lt;com.hjq.shape.view.ShapeView
    android:layout_width="match_parent"
    android:layout_height="20dp"
    app:shape_shadowColor="@color/black"
    app:shape_shadowOffsetY="5dp"
    app:shape_shadowSize="5dp"
    app:shape_solidColor="@color/white" />
</pre>
1. 必须设置<code>shape_solidColor</code>才有阴影吗?
2. 轮轮哥能不能加1个属性<code>shape_shadowShowSide</code>啊. 目前的效果是四个方向都有阴影, 当ShapeView宽度是MatchParent的时候, 左右2边的阴影会导致ShapeView宽度看起来不能全屏, 有间隙, 效果如下:
![image](https://github.com/user-attachments/assets/2c1d89f9-f6d1-434d-be79-7a092f9d0435)
我的建议是加上这个属性<code>app:shape_shadowShowSide="Start|Top|End|Bottom"</code>

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by actor20170211030627** [comment]
需求是这个样子的:
![image](https://github.com/user-attachments/assets/e3fac677-9f15-42db-ab87-cd73c91f4bda)

**Comment by getActivity** [comment]
框架绘制阴影的逻辑，本质是用了 `canvas.drawRect` 实现（绘制一个矩形），这个 API 并不能针对某一边的阴影进行绘制。

**Comment by actor20170211030627** [comment]
好的
